version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    environment:
      - DB_CONNECTION: circle_testing
    working_directory: ~/src
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: change directory work
          command: cd ./src
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/composer.json" }}
      - run:
          name: Install PHP libraries
          working_directory: src
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "src/composer.json" }}
      - run:
          name: Run PHPUnit
          working_directory: src
          command: vendor/bin/phpunit
